DROP TABLE IF EXISTS TBL_RESERVE;

DROP TABLE IF EXISTS TBL_RESERVATION_TABLE;
 
CREATE TABLE TBL_RESERVATION_TABLE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  seats INT NOT NULL,
  seat_cordinates VARCHAR(250) NOT NULL,
  is_reservable BOOLEAN DEFAULT TRUE
);

CREATE TABLE TBL_RESERVE (
  reservation_id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  reserved_by VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  phone VARCHAR(30) NOT NULL,
   reserved_date VARCHAR(250) NOT NULL,
   id INT,
    FOREIGN KEY(id) REFERENCES TBL_RESERVATION_TABLE
);